export const GET_DOGS = "GET_DOGS";
export const GET_NAME_BY_BREENDS = "GET_NAME_BY-BREENDS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const FILTER_BY_TEMPERAMENT= "FILTER_BY_TEMPERAMENT";
export const ORDER_BY_NAME = "ORDER_BY_NAME";